### ISSUE TITLE
allowFailBuild in the extension doesn't work

### ISSUE THREAD

**Issue by hongtatyew** [jfrog/artifactory-vsts-extension#386]
### Describe the bug

I'm trying to setup build pipeline in Azure DevOps and I would like to fail the build if I found any vulnerabilities in the packages. I'm following [this article](https://www.jfrog.com/confluence/display/JFROG/JFrog+Azure+DevOps+Extension#JFrogAzureDevOpsExtension-ScanningPublishedBuildsforSecurityVulnerabilitieswithJFrogXray) to setup the pipeline. No matter how I set `allowFailBuild` in JFrog Audit task, the task couldn't fail. See the image below for the output.

![image](https://user-images.githubusercontent.com/24507078/224943984-fa8d0d50-4cfb-4735-a587-ad3323cc2e3f.png)

```yaml
         - task: JFrogDotnetCore@1
            displayName: "DotNet restore"
            inputs:
              command: "restore"
              artifactoryConnection: "jfrog-artifactory" # only support JFrog artifact username and password service connection, token base authentication will not work
              targetResolveRepo: "central-shared-nuget"
              rootPath: "**/*.sln"
              collectBuildInfo: true
              buildName: "$(Build.DefinitionName)"
              buildNumber: "$(Build.BuildNumber)"
              includeEnvVars: true

          - task: JFrogAudit@1
            displayName: "Audit packages for vulnerabilities with JFrog Xray"
            inputs:
              xrayConnection: "jfrog-xray"
              workingDirectory: "$(System.DefaultWorkingDirectory)"
              watchesSource: "watches"
              watches: "$(JFrog.WatchName)"
              allowFailBuild: true # expect this task to be failed.
          
          - task: JFrogAudit@1
            displayName: "Audit packages for vulnerabilities with JFrog Xray"
            inputs:
              xrayConnection: "jfrog-xray"
              workingDirectory: "$(System.DefaultWorkingDirectory)"
              watchesSource: "watches"
              watches: "$(JFrog.WatchName)"
              allowFailBuild: false
```

Besides, I also find out `allowFailBuild` doesn't work with the following too: 
- `JFrogBuildScan@1`
- `JFrogDocker@1`
- `JFrogAudit@1`

### Current behavior

2023-03-14T07:34:58.0795075Z ##[section]Starting: Audit packages for vulnerabilities with JFrog Xray
2023-03-14T07:34:58.0803230Z ==============================================================================
2023-03-14T07:34:58.0803501Z Task         : JFrog Audit
2023-03-14T07:34:58.0803636Z Description  : Audit the project for security vulnerabilities.
2023-03-14T07:34:58.0803830Z Version      : 1.4.1
2023-03-14T07:34:58.0803973Z Author       : JFrog
2023-03-14T07:34:58.0804106Z Help         : [More Information](https://www.jfrog.com/confluence/display/JFROG/JFrog+Azure+DevOps+Extension#JFrogAzureDevOpsExtension-AuditProjectforSecurityVulnerabilitieswithJFrogXray)
2023-03-14T07:34:58.0804524Z ==============================================================================
2023-03-14T07:34:58.7499691Z 07:34:58 [Info] Using server ID 'SoftwareArtifactRepository.Host.Web_0.1.0-add-ci-cd-pipeline.69_xray_audit_1678779298310' ().
2023-03-14T07:34:58.7526211Z Found tool in cache: jf 2.34.6 x64
2023-03-14T07:34:58.7527286Z Running jfrog-cli from /opt/hostedtoolcache/jf/2.34.6/x64/jf.
2023-03-14T07:34:58.7527866Z JFrog CLI version: 2.34.6
2023-03-14T07:34:58.7535870Z Executing JFrog CLI Command: /opt/hostedtoolcache/jf/2.34.6/x64/jf c add "SoftwareArtifactRepository.Host.Web_0.1.0-add-ci-cd-pipeline.69_xray_audit_1678779298310" --xray-url="***" --interactive=false --user='***' --password=*** --basic-auth-only
2023-03-14T07:34:58.7537122Z Executing JFrog CLI Command: /opt/hostedtoolcache/jf/2.34.6/x64/jf c use "SoftwareArtifactRepository.Host.Web_0.1.0-add-ci-cd-pipeline.69_xray_audit_1678779298310"
2023-03-14T07:34:58.7540263Z Executing JFrog CLI Command: /opt/hostedtoolcache/jf/2.34.6/x64/jf audit --server-id="SoftwareArtifactRepository.Host.Web_0.1.0-add-ci-cd-pipeline.69_xray_audit_1678779298310" --fail=true --watches="incubator-watch"
2023-03-14T07:34:58.7541981Z 07:34:58 [Info] Auditing project: 
2023-03-14T07:34:58.7542342Z 07:34:58 [Info] Detected: nuget, dotnet.
2023-03-14T07:35:03.4341753Z 07:35:03 [Info] JFrog Xray version is: 3.67.9
2023-03-14T07:35:03.4343472Z 07:35:03 [Info] Scanning module Orsted.SoftwareArtifactRepository.RestfulApi...
2023-03-14T07:35:03.6106916Z 07:35:03 [Info] Waiting for scan to complete...
2023-03-14T07:35:19.0945548Z 07:35:19 [Info] Scanning module Orsted.SoftwareArtifactRepository...
2023-03-14T07:35:19.2159769Z 07:35:19 [Info] Waiting for scan to complete...
2023-03-14T07:35:24.7569330Z 07:35:24 [Info] Scanning module Orsted.SoftwareArtifactRepository.Repository...
2023-03-14T07:35:24.7570529Z 07:35:24 [Info] Waiting for scan to complete...
2023-03-14T07:35:29.6923455Z 07:35:29 [Info] Scanning module Orsted.SoftwareArtifactRepository.Service...
2023-03-14T07:35:29.8081754Z 07:35:29 [Info] Waiting for scan to complete...
2023-03-14T07:35:35.0442909Z 07:35:35 [Info] Scanning module Orsted.SoftwareArtifactRepository.Tests...
2023-03-14T07:35:35.1686526Z 07:35:35 [Info] Waiting for scan to complete...
2023-03-14T07:35:40.3814516Z 07:35:40 [Info] Scanning module Orsted.SoftwareArtifactRepository.Localization...
2023-03-14T07:35:40.4960099Z 07:35:40 [Info] Waiting for scan to complete...
2023-03-14T07:35:45.6904620Z 07:35:45 [Info] Scanning module Orsted.SoftwareArtifactRepository.Shared...
2023-03-14T07:35:45.8177638Z 07:35:45 [Info] Waiting for scan to complete...
2023-03-14T07:35:51.0332999Z 07:35:51 [Info] Scanning module Orsted.SoftwareArtifactRepository.WorkerService...
2023-03-14T07:35:51.1876449Z 07:35:51 [Info] Waiting for scan to complete...
2023-03-14T07:36:01.5426314Z 07:36:01 [Info] Scanning module Orsted.SoftwareArtifactRepository.ConsoleApp...
2023-03-14T07:36:01.6836877Z 07:36:01 [Info] Waiting for scan to complete...
2023-03-14T07:36:12.0236256Z 07:36:12 [Info] Scanning module Orsted.SoftwareArtifactRepository.JFrog...
2023-03-14T07:36:12.1425855Z 07:36:12 [Info] Waiting for scan to complete...
2023-03-14T07:36:17.3671125Z 07:36:17 [Info] Scanning module Orsted.SoftwareArtifactRepository.Queries...
2023-03-14T07:36:17.4935547Z 07:36:17 [Info] Waiting for scan to complete...
2023-03-14T07:36:22.7018464Z 07:36:22 [Info] Scanning module Orsted.SoftwareArtifactRepository.Service.Tests...
2023-03-14T07:36:22.8393200Z 07:36:22 [Info] Waiting for scan to complete...
2023-03-14T07:36:28.1033202Z 07:36:28 [Info] Scanning module Orsted.SoftwareArtifactRepository.JFrog.Tests...
2023-03-14T07:36:28.2204971Z 07:36:28 [Info] Waiting for scan to complete...
2023-03-14T07:36:33.4368150Z 07:36:33 [Info] Scanning module Orsted.SoftwareArtifactRepository.RestfulApi.Tests...
2023-03-14T07:36:33.5877300Z 07:36:33 [Info] Waiting for scan to complete...
2023-03-14T07:36:38.8090887Z The full scan results are available here: /tmp/jfrog.cli.temp.-1678779398-3585804344
2023-03-14T07:36:38.8091994Z Security Violations
2023-03-14T07:36:38.8093202Z +----------+---------------------------+------------+---------------------------+------------+----------+-------+----------------+
2023-03-14T07:36:38.8094023Z | SEVERITY | DIRECT                    | DIRECT     | IMPACTED                  | IMPACTED   | FIXED    | TYPE  | CVE            |
2023-03-14T07:36:38.8094738Z |          | DEPENDENCY                | DEPENDENCY | DEPENDENCY                | DEPENDENCY | VERSIONS |       |                |
2023-03-14T07:36:38.8095359Z |          |                           | VERSION    | NAME                      | VERSION    |          |       |                |
2023-03-14T07:36:38.8096232Z +----------+---------------------------+------------+---------------------------+------------+----------+-------+----------------+
2023-03-14T07:36:38.8097310Z | Critical | Orsted.WorkerApp          | 2.0.3      | System.Drawing.Common     | 4.7.0      | [4.7.2]  | NuGet | CVE-2021-24112 |
2023-03-14T07:36:38.8098495Z |          | Orsted.ConsoleApp         | 2.0.3      |                           |            | [5.0.3]  |       |                |
2023-03-14T07:36:38.8104140Z +----------+---------------------------+------------+---------------------------+------------+----------+-------+----------------+
2023-03-14T07:36:38.8105304Z | High     | Microsoft.VisualStudio.We | 7.0.3      | System.Text.RegularExpres | 4.3.0      | [4.3.1]  | NuGet | CVE-2019-0820  |
2023-03-14T07:36:38.8106112Z |          | b.CodeGeneration.Design   |            | sions                     |            |          |       |                |
2023-03-14T07:36:38.8106720Z |          | xunit                     | 2.4.2      |                           |            |          |       |                |
2023-03-14T07:36:38.8107311Z |          | Orsted.WorkerApp          | 2.0.3      |                           |            |          |       |                |
2023-03-14T07:36:38.8107942Z |          | Orsted.ConsoleApp         | 2.0.3      |                           |            |          |       |                |
2023-03-14T07:36:38.8108545Z |          | Microsoft.NET.Test.Sdk    | 17.3.2     |                           |            |          |       |                |
2023-03-14T07:36:38.8109451Z +----------+---------------------------+------------+---------------------------+------------+----------+-------+----------------+
2023-03-14T07:36:38.8110395Z | High     | xunit                     | 2.4.2      | System.Net.Http           | 4.3.0      | [4.3.4]  | NuGet | CVE-2018-8292  |
2023-03-14T07:36:38.8111353Z +----------+---------------------------+------------+---------------------------+------------+----------+-------+----------------+
2023-03-14T07:36:38.8112179Z +---------------------------------------------+
2023-03-14T07:36:38.8113007Z | No license compliance violations were found |
2023-03-14T07:36:38.8113651Z +---------------------------------------------+
2023-03-14T07:36:38.8125699Z Executing JFrog CLI Command: /opt/hostedtoolcache/jf/2.34.6/x64/jf c remove "SoftwareArtifactRepository.Host.Web_0.1.0-add-ci-cd-pipeline.69_xray_audit_1678779298310" --quiet
2023-03-14T07:36:38.8279532Z ##[section]Finishing: Audit packages for vulnerabilities with JFrog Xray

### Reproduction steps

Run the following tasks:
- `JFrogBuildScan@1`
- `JFrogDocker@1`
- `JFrogAudit@1`

### Expected behavior

If any of the tasks below find any vulnerabilities in the build, it should fail the build.
- `JFrogBuildScan@1`
- `JFrogDocker@1`
- `JFrogAudit@1`

### Azure DevOps extension name and version

JFrog 2.4.1

### JFrog CLI version

JFrog CLI version: 2.34.6

### Operating system type and version

ubuntu-latest

### JFrog Artifactory version (if relevant)

1.4.1

### JFrog Xray version (if relevant)

1.4.1

### JFrog Distribution version (if relevant)

1.4.1
