### ISSUE TITLE
Missing parameter configuration from "Conan add remote" task

### ISSUE THREAD

**Issue by DavidRadoorHummel** [jfrog/artifactory-vsts-extension#429]
### Describe the bug

When using the Task `JFrog Conan` with the command `Add remote` it does not contain fields with build name or build number:

![image](https://github.com/jfrog/jfrog-azure-devops-extension/assets/86228169/b2a79f2c-eb60-48a0-9da4-dd2057deda60)

However, if you change the build info values, in a prior Conan task, such that you do not use the default, ie:

`$(Build.DefinitionName)`

and

`$(Build.BuildNumber)`

This task will fail with: `Failed to execute Conan Task: Failed to setup Build Info collection: Conan artifacts.properties file exists at D:\builds\a1\1129\20230616.3\.conan\artifacts.properties with different build info values.`

The task _does_ support supplying build name and build number, but that is not visible from the UI.

This means you can still invoke the task as:

``` yaml
- task: JFrogConan@1
  inputs:
    conanCommand: 'Add Remote'
    remoteName: 'ConanPublishRepo'
    artifactoryConnection: ${{ parameters.artifactoryConnection }}
    conanRepo: '${{ parameters.publishRepo }}'
    purgeExistingRemotes: false
    buildName: '${{ parameters.buildName}}'
    buildNumber: '${{ parameters.buildNumber}}'
  displayName: 'Add Conan Remote For Artifactory'
```

### Current behavior

The parameters for build name and build number are missing from the UI of `JFrog Conan` with the command `Add remote`.
The parameters _do_ exist, but they're missing from the UI.

### Reproduction steps

Create two tasks in an Azure pipeline from the UI:

1. `JFrog Conan` with `Conan Create` command with customized build name and number.
2. `JFrog Conan` with `Add Remote` command
3. Run the pipeline

Pipeline will fail in step 2 with:

 `Failed to execute Conan Task: Failed to setup Build Info collection: Conan artifacts.properties file exists at D:\builds\a1\1129\20230616.3\.conan\artifacts.properties with different build info values.`

### Expected behavior

The parameters for build name and build number is present in the UI of the `JFrog Conan` task with the command `Add Remote`

### Azure DevOps extension name and version

JFrog 2.6.4 (Latest)

### JFrog CLI version

2.37.3

### Operating system type and version

Windows 10
