### ISSUE TITLE
JFrogDotnetCore@1  "push" command does not use DotNet core

### ISSUE THREAD

**Issue by DavidRadoorHummel** [jfrog/artifactory-vsts-extension#453]
### Describe the bug

The task JFrogDotnetCore@1 with the command "push" does not use DotNet Core, but simply uses JFrog CLI (only). This means that any DotNet core specific arguments are not used.

For example:

```
- task: JFrogDotnetCore@1
  inputs:
    command: 'push'
    arguments: '--skip-duplicate'
    artifactoryConnection: ${{ parameters.artifactoryConnection }}
    targetDeployRepo: '${{ parameters.deployRepo }}'
    pathToNupkg: '${{ parameters.pathToNupkg }}'
    collectBuildInfo: true
    includeEnvVars: true
    buildName: '${{ parameters.buildName}}'
    buildNumber: '${{ parameters.buildNumber}}'
  displayName: 'Publish Nuget Package(s) To Artifactory'
  continueOnError: false
```

And the output command in the pipeline is:

`/__t/jf/2.44.1/x64/jf rt u "/__w/29/a/NugetPackages/MyPackage.*.nupkg" "nuget-snapshot-local" --server-id="MyId" --flat="true" --build-name="MyBuild" --build-number="1"`

Notice that it is not `jf rt dotnet nuget push` but simply `jf rt u`. Additionally, the argument `--skip-duplicate` is ignored.

### Current behavior

The task JFrogDotnetCore@1 is not using "DotNet core" with JFrog CLI, but simply uses JFrog CLI and ignores DotNet specific arguments.

### Reproduction steps

* Create a pipeline that uploads a nuget package with the task JFrogDotnetCore@1 and the push command
* Notice how, in the pipeline output, it does not use jf rt dotnet`` 

### Expected behavior

The task JFrogDotnetCore@1 uses `jf rt dotnet` command and uses the arguments specified.

### Azure DevOps extension name and version

2.8.0 (Latest)

### JFrog CLI version

2.44.1 x64

### Operating system type and version

Windows 10
