### ISSUE TITLE
ArtifactoryNpm@2 'pack and publish' package within a monorepo of yarn workspaces?

### ISSUE THREAD

**Issue by ghost** [jfrog/artifactory-vsts-extension#466]
(Where is the documentation for Azure DevOps "ArtifactoryNpm@2" task?)

In a Yarn workspaces monorepo, the root workspace is necessarily private and not publishable.

I have:

- example/package.json (workspace)
- lib/package.json (workspace)
- package.json (root workspace)
- yarn.lock

as a CI bash script, I could just run `yarn workspace @my/lib npm publish` but the CI agent doesn't have the credentials there.  I assume we need to use the specialized `ArtifactoryNpm@2` yaml pipeline task, but I can't find documentation/examples/discussions/bugs about how this should be accomplished.  I'm not even sure this is the right github repo to ask about this.  Any help, please?

**Comment by JasonKleban** [comment]
This kinda works, except the guess of `arguments: '--tag next'` is ineffective

```
- task: ArtifactoryNpm@2
  inputs:
    command: 'pack and publish'
    artifactoryService: 'Artifactory'
    workingFolder: "lib/"
    arguments: '--tag next'
    targetRepo: 'jfroggy'
  displayName: Publish Next
```
