### ISSUE TITLE
JFrogToolsInstaller@1 : Error occurred while executing task: Failed while attempting to download JFrog CLI - 404 error

### ISSUE THREAD

**Issue by Saba42V** [jfrog/artifactory-vsts-extension#524]
### Describe the bug

We configured remote repo for downloading and caching V2 Jfrog CLI.

Below task was executed to download and got below reported error 404 due to task is looking for incorrect CLI tool name. We find this seems to be bug because the task is looking for "https://xxxxxx.jfrog.io/artifactory/zip.remote.jfrog.cli.v2/2.72.3/jfrog-cli-linux-amd64/jf" instead it should look for "https://xxxxxx.jfrog.io/artifactory/zip.remote.jfrog.cli.v2/2.72.3/jfrog-cli-linux-amd64/jfrog" as per "https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.72.2/jfrog-cli-linux-amd64/"

```yaml

- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'JFrog-Artifactory-V2'
    cliInstallationRepo: 'zip.remote.jfrog.cli.v2'
    installCustomVersion: true
    cliVersion: '2.72.3'

```

CI/CD error

Downloading: https://XXXX.jfrog.io/artifactory/zip.remote.jfrog.cli.v2/2.72.3/jfrog-cli-linux-amd64/jf
##[error]Error occurred while executing task: Failed while attempting to download JFrog CLI from
 
https://xxxxxx.jfrog.io/artifactory/zip.remote.jfrog.cli.v2/2.72.3/jfrog-cli-linux-amd64/jf

If the chosen Artifactory Service cannot access the internet, you may also manually download version 2.72.3 of JFrog CLI and place it on the agent in the following path: /opt/hostedtoolcache/_jf/current/jf
Error: Unexpected HTTP response: 404
Finishing: JFrogToolsInstaller

Hope you will fix this bug as soon as possible changing tool installer name form /jf to /jfrog in lookup URL as per "https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.72.2/jfrog-cli-linux-amd64/"

### Current behavior

Downloading: https://XXXX.jfrog.io/artifactory/zip.remote.jfrog.cli.v2/2.72.3/jfrog-cli-linux-amd64/jf
##[error]Error occurred while executing task: Failed while attempting to download JFrog CLI from
 
https://xxxxxx.jfrog.io/artifactory/zip.remote.jfrog.cli.v2/2.72.3/jfrog-cli-linux-amd64/jf

If the chosen Artifactory Service cannot access the internet, you may also manually download version 2.72.3 of JFrog CLI and place it on the agent in the following path: /opt/hostedtoolcache/_jf/current/jf
Error: Unexpected HTTP response: 404
Finishing: JFrogToolsInstaller

### Reproduction steps

Run below tool installer task by creating remote repo(zip.remote.jfrog.cli.v2) with URL "https://releases.jfrog.io/artifactory/jfrog-cli/v2/"

- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'JFrog-Artifactory-V2'
    cliInstallationRepo: 'zip.remote.jfrog.cli.v2'
    installCustomVersion: true
    cliVersion: '2.72.3'

### Expected behavior

The tool installer task should look for downloading https://xxxxxx.jfrog.io/artifactory/zip.remote.jfrog.cli.v2/[version]/[ostype]/jfrog

### Azure DevOps extension name and version

 New JFrog Azure Devops Extension

### JFrog CLI version

'2.72.3'

### Operating system type and version

Ubuntu-latest

**Comment by Saba42V** [comment]
Updating Jfrog remote repo(zip.remote.jfrog.cli.v2) with URL from "https://releases.jfrog.io/artifactory/jfrog-cli/v2/" to https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/ is fixing the issue.

However, want to check is this how it is expected usage as we are loosing to use CLI cmd `jfrog` and we have to use `jf`

**Comment by Saba42V** [comment]
Jfrog technical support team response:

Regarding your query, I have tested this in my lab environment and I am able to reproduce the issue. Please be informed that I am checking this with internal teams and update you with the details.

Regarding the usage, The legacy name of JFrog CLI's executable is jfrog. In an effort to make the CLI usage easier and more convenient, we recently exposed a series of new installers, which install JFrog CLI with the new jf executable name. For backward compatibility, the old installers will remain available. We recommend migrating to the newer jf executable name.

**Comment by Saba42V** [comment]
For now we enabled two solutions:

1. Configure remote repo to use cli cmd invoking using "Jf" by downloading the cli installer
Configure Jfrog remote repo(zip.remote.jfrog.cli.v2) with URL https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/

```yaml
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'JFrog-Artifactory-V2'
    cliInstallationRepo: 'zip.remote.jfrog.cli.v2'
    installCustomVersion: true
    cliVersion: '2.72.3'
```
3. Use below azure devops task to run cli cmd directly in the build machine using "jf"

```yaml
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'JFrog-Platform-V2'
    command: |
      jf intro

- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'JFrog-Platform-V2'
    useCustomVersion: true
    cliVersion: '$(jfrogCliVersion)'
    command: |
      jf intro
      jf <Command>
```
